name: Roll back Docker image deployment in ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  roll-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine previous version number
        run: |
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags HEAD^)
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create or update ECS service with previous Docker image
        env:
          IMAGE_NAME: my-image
          TAG: ${{ steps.determine-previous-version.outputs.previous_tag }}
        run: |
          aws deploy create-deployment \
            --application-name my-application \
            --deployment-group-name my-deployment-group \
            --revision '{"revisionType":"Docker","dockerImageName":"'$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$TAG'"}'

      - name: Wait for deployment to complete
        run: |
          while true; do
            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query "deploymentInfo.status" --output text)
            if [[ "$STATUS" == "Succeeded" ]]; then
              echo "Deployment successful!"
              break
            elif [[ "$STATUS" == "Failed" ]]; then
              echo "Deployment failed."
              exit 1
            else
              echo "Deployment in progress..."
              sleep 30
            fi
          done
