name: Build and deploy Docker image to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          if [[ "$LATEST_TAG" == "" ]]; then
            NEW_TAG="1.0.0"
          else
            SEMVER_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
            if [[ "$LATEST_TAG" =~ $SEMVER_REGEX ]]; then
              MAJOR="${BASH_REMATCH[1]}"
              MINOR="${BASH_REMATCH[2]}"
              PATCH="${BASH_REMATCH[3]}"
              NEW_TAG="v$MAJOR.$MINOR.$((PATCH+1))"
            fi
          fi
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Build Docker image
        env:
          IMAGE_NAME: my-image
          TAG: ${{ steps.determine-version.outputs.new_tag }}
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create or update ECS service
        env:
          IMAGE_NAME: my-image
          TAG: ${{ steps.determine-version.outputs.new_tag }}
        run: |
          aws deploy create-deployment \
            --application-name my-application \
            --deployment-group-name my-deployment-group \
            --revision '{"revisionType":"Docker","dockerImageName":"'$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$TAG'"}'

      - name: Wait for deployment to complete
        run: |
          while true; do
            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query "deploymentInfo.status" --output text)
            if [[ "$STATUS" == "Succeeded" ]]; then
              echo "Deployment successful!"
              break
            elif [[ "$STATUS" == "Failed" ]]; then
              echo "Deployment failed."
              exit 1
            else
              echo "Deployment in progress..."
              sleep 30
            fi
          done
