
name: Amazon ECS deploy

on:
   workflow_dispatch: 
  #  push:
  #       branches: [main]

# env:
#   AWS_REGION: ap-south-1                   # set this to your preferred AWS region, e.g. us-west-1
#   ECR_REPOSITORY: ga-ecs           # set this to your Amazon ECR repository name
#   ECS_SERVICE: ecs-deploy-service                 # set this to your Amazon ECS service name
#   ECS_CLUSTER: github-action-ecs                 # set this to your Amazon ECS cluster name
#   ECS_TASK_DEFINITION: .github/workflows/task-definition.json # set this to the path to your Amazon ECS task definition
#                                                # file, e.g. .aws/task-definition.json
#   CONTAINER_NAME: ecs-deploy-container          # set this to the name of the container in the
#   IMAGE_NAME: 168082689495.dkr.ecr.ap-south-1.amazonaws.com/ga-ecs:7777777                                           # containerDefinitions section of your task definition

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing
        uses: actions/setup-node@v3
        with:
          node-version: '12'
      - run: npm install
      - run: npm run test