name: Build and Deploy React App to CloudFront
on:
  # workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: github-action-nginx
      DIST: build
      REGION: ap-south-1
      DIST_ID: E118ZAQXPR2IFW

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Assign or Get Tag
      id: get-tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: delta-bravo277
        WITH_V: true
        DEFAULT_BUMP: none
        DRY_RUN: false
        
    - name: Print tag
      id: determine-tag
      env:
        NEW_TAG: ${{ steps.get-tag.outputs.tag }}
        PART: ${{ steps.get-tag.outputs.part }}
      run: |
        echo $NEW_TAG
        echo $PART

    - name: Configure AWS Credentials v2
      if: ${{ steps.get-tag.outputs.part != '0' || steps.get-tag.outputs.part != '' }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # role-to-assume: ${{ secrets.AWS_GA_ROLE }}
        aws-region: ${{ env.REGION }}

    - uses: actions/setup-node@v2
      if: ${{ steps.get-tag.outputs.part != '0' || steps.get-tag.outputs.part != '' }}
      with:
        node-version: '12'

    - name: Install Dependencies
      if: ${{ steps.get-tag.outputs.part != '0' || steps.get-tag.outputs.part != '' }}
      run: |
        node --version
        npm install

    - name: Build Static Website
      if: ${{ steps.get-tag.outputs.part != '0' || steps.get-tag.outputs.part != '' }}
      run: |
         npm run build

    - name: Copy files to the production website with the AWS CLI
      if: ${{ steps.get-tag.outputs.part != '0' || steps.get-tag.outputs.part != '' }}
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}/${{ steps.get-tag.outputs.tag }}/

    - name: Cloudfront Cache Invalidation
      if: ${{ steps.get-tag.outputs.part != '0' || steps.get-tag.outputs.part != '' }}
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"
