name: Rollback and Deploy to CloudFront
on:
   workflow_dispatch:
jobs:
  build-and-deploy:
    name: Rollback and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: github-action-nginx
      DIST: build
      REGION: ap-south-1
      DIST_ID: E118ZAQXPR2IFW

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: 
          PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          echo $PREV_TAG