name: Rollback and Deploy to CloudFront
on:
   workflow_dispatch:
jobs:
  build-and-deploy:
    name: Rollback and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: github-action-nginx
      DIST: build
      REGION: ap-south-1
      DIST_ID: E118ZAQXPR2IFW
      S3_CLOUDFRONT_ORIGIN_ID: github-action-nginx.s3.ap-south-1.amazonaws.com

    steps:
    - name: Checkout  
      uses: actions/checkout@v3     #To fetch the history (including tags) from within a shallow clone
    - run: |
          git fetch --prune --unshallow 
          PREV_TAG=$(git tag | tail -n2 | head -n1)
          git checkout tags/$PREV_TAG

    - name: get Tag
      id: tag
      run: |
          git fetch --prune --unshallow 
          echo "GET_TAG=$(git tag | tail -n2 | head -n1)" >> $GITHUB_OUTPUT
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Update Cloudfront Distribution
      env:
        CURR: ${{ steps.tag.outputs.GET_TAG }}
      run: |

        aws cloudfront get-distribution-config \
        --id ${{ env.DIST_ID }} --region ${{ env.REGION }} > output.json

        cat output.json | jq "del(.ETag) | (.DistributionConfig.Origins.Items[] | select(.Id == \"${{ env.S3_CLOUDFRONT_ORIGIN_ID }}\")).OriginPath = \"/${{ steps.tag.outputs.GET_TAG }}\" | .DistributionConfig" > updated-config.json

        etag=`cat output.json | jq -r ".ETag"`

        aws cloudfront update-distribution \
        --id ${{ env.DIST_ID }}  --region ${{ env.REGION }} --if-match="$etag" \
        --distribution-config file://updated-config.json
